remote_theme: sighingnow/jekyll-gitbook
title: NJKIAB recipe bookmarks
description: Recipes
page_excerpts: true
toc:
    enabled: true
    h_min: 1
    h_max: 3

tracker:
  google_analytics: "<G-5VDN5899X9>"
  
[//]: # (Theme from https://sighingnow.github.io/jekyll-gitbook/)
